### ISSUE TITLE
Capture, surface last-modified date on foundation metadata

### ISSUE THREAD

**Issue by apetro** [ShaneCurcuru/chooseafoundation#11]
Idea: for each Foundation record, capture a last-updated date, so that the site, the reader can get an idea of how current the information might be.

This might help to mitigate staleness in specifics. As in, here's the specific number of projects this foundation sponsored *as of a specific date*.

Having these dates as metadata might allow the site to appropriately de-emphasize or warn viewers about stale data, or could surface to a TODO page highlighting what data's needing re-validation, or...

**Comment by ShaneCurcuru** [comment]
Agreed.  Does someone have a github-pages automated way to display the last date a file was committed that will show up in the output?

**Comment by ShaneCurcuru** [comment]
Jekyll does this with a hook, but it doesn't work when using Github Pages to autopublish:
https://github.com/jekyll/jekyll/issues/2260

There's gotta be a tiny JavaScript bit that can insert this client-side from some GH API (or silently fail, in case of errors).

**Comment by apetro** [comment]
Under-engineering this as a manually curated date in the YAML front-matter might be the best way to go, at least initially. The last time the file was touched *isn't* necessarily the relevant freshness date from a user expectations perspective -- a file might have been touched to fix a typo without curating its substantive content, say. Out of the gate it's just a few files so not much overhead to twiddle the date field on substantive modify -- this will be good enough until it isn't.

**Comment by ShaneCurcuru** [comment]
Fixed with a manually updated date as suggested in 3c8e268
Thanks!
