### ISSUE TITLE
OW2 page formatting

### ISSUE THREAD

**Issue by slauriere** [ShaneCurcuru/chooseafoundation#15]
It seems the page at http://chooseafoundation.com/foundations/ow2 is not properly formatted by the site generator.

**Comment by ShaneCurcuru** [comment]
Weird - there's some strange YAML parsing error on just this file that I can't figure out yet.

Error: could not read file /chooseafoundation/_foundations/ow2.md: (<unknown>): did not find expected key while parsing a block mapping at line 53 column 3

**Comment by ShaneCurcuru** [comment]
Should be fixed in be10659fb7d81465cc76ee3e0a658084828a3b56
