### ISSUE TITLE
Is the project still actively developed?

### ISSUE THREAD

**Issue by amottier** [ShaneCurcuru/chooseafoundation#22]
As I don't see any comment on #19, #20 and #21 I was wondering if it is still under active development?

Thanks.

**Comment by ShaneCurcuru** [comment]
Apologies - I've had various health issues and have taken time off from open source recently, but I'm coming back now. Thanks for the polite reminder, will start responding to issues in the next week or so.

**Comment by amottier** [comment]
Thanks a lot for the update and I hope your are fully recovering from your health issue.

**Comment by kendallnelson** [comment]
Speedy recovery!
