### ISSUE TITLE
Avoid specifc number of projects hosted

### ISSUE THREAD

**Issue by tbm** [ShaneCurcuru/chooseafoundation#4]
Currently you list the specific number of projects hosted by an org (e.g. 45 for SPI right now).  This will be a headache to keep up to date.

How about categories, e.g. 0-50, 50-100.  Not sure what the right categories are but I think this approach makes more sense.

**Comment by ShaneCurcuru** [comment]
ACK, I am undecided on that one.  This isn't an always-accurate set of details; it's meant to be enough overview information that FOSS projects can start making their own decision who to approach.
Also, I should note that this is counting the equivalent of Apache top level projects: i.e. not counting incubator or probationary projects, small labs, or other side work.  Thus a "project" is a community of people working on a specific named technology together that has some obvious deliverable (software releases, possibly major standards documentation packages, etc.)

**Comment by apetro** [comment]
Showing the date a foundation's record was last updated ( #11  ) might mitigate this.

**Comment by ShaneCurcuru** [comment]
While this kind of metric has slightly different meanings in various communities, I think it's still important. I definitely hope to include last date updated #11 soonish to address.
