### ISSUE TITLE
Suggested resources

### ISSUE THREAD

**Issue by tbm** [ShaneCurcuru/chooseafoundation#5]
Here are some articles you may want to mention in the resources section:

Non-profits, foundations, and umbrella organizations
https://lwn.net/Articles/561336/

LFCS: The value of FOSS fiscal sponsorship
https://lwn.net/Articles/548542/

Fundraising 101 from the Community Leadership Summit
https://lwn.net/Articles/560381/

**Comment by ShaneCurcuru** [comment]
I'm still figuring out how many resources to include - I'm planning over time to add sections for governance, community, licenses, etc. each with some explanations and links of curated lists, so will consider these then.  Thx.
